- hosts: webservers

  tasks:
    - name: update apt
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name: install services
      ansible.builtin.import_tasks:
        file: install_tasks.yaml


- name: prepare users
  ansible.builtin.import_playbook: prepare_users.yaml

- name: create webpage
  ansible.builtin.import_playbook: create_webpage.yaml
